a=input('dijite algo:')
print('o tipo primetivo desse valor e?',type(a))
print('so tem espaço?',a.isspace())
print('e um numero?',a.isnumeric())
print('e alfabetico?',a.isalpha())
print('e almunerico?',a.isalnum())
print('estar em maiusculo?',a.isupper())
print('e minusculo?',a.islower())
print('estar capilizado?',a.istitle())
